### ISSUE TITLE
关于FL场景的3个问题

### ISSUE THREAD

**Issue by zkzhu0110** [open-intelligence/federated-learning-chinese#3]
我在调研本翻译书和相关文献的时候，整理出了3个问题，想确认一下，能否方便问一下大家？

【问题1】1.1.1节里有一句话“将模型推送给受约束的客户，以评估本地客户数据”，每个用户的训练集肯定是自己提供的，那么**验证集是不是也是用户自己提供？**

【问题2】3.2节中有一句话“在典型的联邦学习任务重，目标是学习单个全局模型”，换句话说，是不是用户在加入FL计划的时候，**不需要上传自己的模型？**

【问题3】如果用户**需要加密自己的梯度或者其它信息**，**用户需要提供什么信息？**

多谢

**Comment by congjianluo** [comment]
这是我对于三个问题的一个答案，欢迎其他小伙伴进行补充和讨论。

【回答1】在所提到的这句话完整表述是“分析可能包括在**数据中心的标准数据集**上计算的度量矩阵，或者是**联邦评估，其中，将模型推送给受约束的客户，以评估本地客户数据**。”。因此，验证的方式可以认为有两种，需根据联邦场景确定：①在中心节点拥有的标准数据集上（可以通过用户上传，或者中心进行采集等方式获得）；②将模型下发给用户后，用户可以在自己的数据集上进行验证。

【回答2】用户是否需要上传模型需要由事先确定的协议（规则来决定）：如果加入节点有进行独立训练的能力，那么可以**允许节点提供自己当前模型，由中心决定是否采纳到当前模型平均中**；当然，也可以**直接参与到联邦学习中，即在中心直接下发的模型基础上，继续进行本地训练和并参与同步**。
本节3.1节的“数据集飘移”中提到，并不是所有的节点都能够进行训练任务，因此部分节点只能单纯的从中心获得模型，用于用户本地数据的推理。

【回答3】这里的问题有些奇怪，“用户需要加密自己的梯度或者其他信息”，是**用户提供梯度或者其他信息**，**联邦提供加密策略**并要求上传加密后的数据；还是说**用户提供的梯度或者其他信息**已经经过用户自己的加密。
如果是前者，那么**无需用户提供额外信息**，因为联邦的加密策略应当考虑例如：同态加密的直接可加性、联邦需要在确保安全的环境下进行解密等情况。
如果是后者，那么需要**用户明确加密后的梯度或者其他信息的性质**，例如：是否支持加减乘除操作、是否提供额外的用户公钥等。
其实两者差异不大，核心在于中心与用户需要确定采用的加密方式。
