### ISSUE TITLE
重要地方的翻译出现错误

### ISSUE THREAD

**Issue by wangzhenzhou2020** [open-intelligence/federated-learning-chinese#4]
章节： introduction
![image](https://user-images.githubusercontent.com/67401289/108626468-53caae00-748b-11eb-8d47-1f2c291927dd.png)
1处 的翻译 应为 “可编址性”
2、3处 的翻译应该调换

**Comment by congjianluo** [comment]
感谢您的建议，已将：
1处 “Addressability” 更正为 “可寻址性”；
更换2、3处的翻译。
非常感谢。
